name: Run Python Script

on:
  workflow_dispatch:
    inputs:
      sudoku:
        description: "Suite de chiffres du tableau a resoudre" 
        type: string
        required: true

 

          
jobs:
  build:
    runs-on: ensta

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Version de Python
                
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Facultatif si vous avez un fichier requirements.txt
        shell: powershell
         
      - name: Run Python Script
        run: |
          python ./main.py > tempi.txt
          cat tempi.txt >> $GITHUB_OUTPUT
        id: result
        env:
          MY_SUDOKU: ${{ github.event.inputs.sudoku}}

      - name: Print output
        id: output
        run: echo "${{steps.result.outputs.MY_OUTPUT}}"
