name: Run Python Script

on:
  workflow_dispatch:
    inputs:
      which-url:
        description: "Tableau a resoudre" 
        type: string
        required: true

          
jobs:
  run-python-script:
    runs-on: thinkpad

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Version de Python

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Facultatif si vous avez un fichier requirements.txt

      - name: Run Python Script
        run: ./main.py